const colors = {
  BG_COLOR: "#FFFFFF",
  BLUE: "#4285F4",
  BLACK: "#000000",
  FOOTER: "#100F2F",
  GRAY_SUBHEADER_TEXT: "#8087AB",
  EXPLORE_CARD_TAP: "#E0E0E0",
  SILVER: "#C0C0C0",
  TAB_BAR_BG_COLOR: "#FFFFFF",
  TAB_BAR_ICON_DEFAULT: "#C7CAFF",
  TAB_BAR_ICON_SELECTED: "#5F67EC",
  TAB_BAR_PRESS_COLOR: "#C7CAFF",
  ORANGE: "#FF9056",
  PURPLE_LIGHT: "#C7CAFF",
  PURPLE: "#5F67EC",
  SEARCH_INPUT_TEXT: "#A7AFD7",
  SEARCH_CONTAINER: "#F4F6FD",
  WHITE: "#FFFFFF",
};

export default colors;
