const colors = {
  BG_COLOR: "#FFFFFF",
  GRAY_SUBHEADER_TEXT: "#8087AB",
  TAB_BAR_BG_COLOR: "#FFFFFF",
  TAB_BAR_ICON_DEFAULT: "#C7CAFF",
  TAB_BAR_ICON_SELECTED: "#5F67EC",
  TAB_BAR_PRESS_COLOR: "#C7CAFF",
  ORANGE: "#FF9056",
  PURPLE_LIGHT: "#C7CAFF",
  PURPLE: "#5F67EC",
  SEARCH_INPUT_TEXT: "#A7AFD7",
  SEARCH_CONTAINER: "#F4F6FD",
};

export default colors;
